### ISSUE TITLE
Bug in pregnancy lens

### ISSUE THREAD

**Issue by jkiddo** [Gravitate-Health/lens-selector-mvp2#10]
As stated on https://github.com/Gravitate-Health/fhir-connector/issues/2 - it seems that there is a bug in the lens. If a wrong SNOMED code is added for pregnancy the section gets annotated anyway.

**Comment by aalonsolopez** [comment]
Just to be 100% sure that I understand what you are doing, you are changing inside the ePI from this
``` json
"url": "concept",
          "valueCodeableReference": {
            "concept": {
              "coding": [ {
                "system": "http://snomed.info/sct"
                "code": "77386006",
                "display": "Pregnancy"
              } ]
            }
          }
```
to this

```json

"url": "concept",
          "valueCodeableReference": {
            "concept": {
              "coding": [ {
                "system": ["http://snomed.info/sct"](http://snomed.info/sct),
                "code": "77386006kqweoiqe",
                "display": "Pregnancy"
              } ]
            }
          }
```

**Comment by jkiddo** [comment]
Nope - I change the contents of the IPS

**Comment by jkiddo** [comment]
From
```
            {
                "resource": {
                    "resourceType": "Observation",
                    "id": "c580512e-12d5-4d03-983d-185df302fe0f",
                    "valueCodeableConcept": {
                        "coding": [
                            {
                                "system": "http://snomed.info/sct",
                                "code": "77386006"
                            }
                        ]
                    }
                }
            }
```
to 
```
            {
                "resource": {
                    "resourceType": "Observation",
                    "id": "c580512e-12d5-4d03-983d-185df302fe0f",
                    "valueCodeableConcept": {
                        "coding": [
                            {
                                "system": "http://snomed.info/sct",
                                "code": "77386006fdksjhflkdsjh"
                            }
                        ]
                    }
                }
            }
```

**Comment by jkiddo** [comment]
The ePI's are under the control of the IG which mostly @joofio controls. Those I consider authorative (to some extent). What I manipulate is the IPS as I'm the source of that information - e.g. messing up the gender and adding/modifying diagnoses.

**Comment by aalonsolopez** [comment]
Perfect. Totally understand. I'll work on it.

**Comment by joofio** [comment]
the code has this meaning:
https://www.findacode.com/snomed/77386006--pregnant.html

my idea is to have a few codes that could be used for the pregancy lenses (so a list of system paired with code ).
That should be the driving factor behind the lenses.

I see the workflow similar to:
1. check epi for one of the code-system pair list in the extension (html class)
2. check if ips data is according to what is intended (is pregnant, or is female, or something else)
3. highlight the tags with class mentioned in 1.

this would be the logic for a lot of different lenses as well.... (with changes on 1. codes and 2. requirements)

@jkiddo this is what you were expecting right?

**Comment by jkiddo** [comment]
yes ... and add e.g age and other criterias to that for the pregnancy lens. Essentially it could mostly be expressed in terms of a FHIR path expression or multiple of those.

**Comment by joofio** [comment]
I was not specifying the ips requirements, but yes age seems fine to me.

Regarding the FHIR path, I also agree, but in the end it is about how it
is/ developers want to implement.


Jens Kristian Villadsen ***@***.***> escreveu no dia quarta,
11/10/2023 à(s) 10:32:

**Comment by jkiddo** [comment]
Sure - its just yet another tool in the belt

**Comment by jkiddo** [comment]
@aalonsolopez / @amedranogil - thinking about this I have an idea. What about turning it around instead. Wouldn't a better idea be for you guys to document what each indiviual lens looks for in the data / IPS in pseudo code / semi human readable languages - pr lens - and put that on e.g. https://github.com/Gravitate-Health/lens-selector-mvp2/wiki or some other place. In that way I as a user of the FOSPS have an idea of how and what is used. Right now, I have to go and look at your code which not really an optimal solution.

**Comment by joofio** [comment]
Jens let your thoughts in here. your proposal resembles mine.
https://github.com/Gravitate-Health/lens-selector-mvp2/issues/7

**Comment by amedranogil** [comment]
Definitely Lenses need some documentation, maybe wiki is not the best option right now. Since the interface for Lenses is designed to evolve, and we are thinking in an open market of lenses (i.e. we should not expect there to be a single provider of lenses); I think the best solution would be to have the lens it self to both provide a static description of what it does, and a link to find where the documentation of the lens is (by adding more functions to be implemented by the lens, this would bump the specification @aalonsolopez, remember our discussion on this and why this returns the version of the specification which the lens is compatible with).
With these extra, self-reporting, information we would then add services for client to query information about the lenses, and then present that information to the user directly.
I think this is important specifications to add for MVP3, for now we should document lenses internally, also because we still have to validate the actual logic of the lenses through the PEG with clinical, legal, and regulatory aspects.

**Comment by amedranogil** [comment]
Documentation of lenses should be handled by the new metadata approach. https://github.com/hl7-eu/gravitate-health/issues/29
