### ISSUE TITLE
[XL] Pipeline lenses: transform lenses to fsh and send encoded to FHIR

### ISSUE THREAD

**Issue by gmej** [Gravitate-Health/lens-selector-mvp2#15]
Lenses build/push will be automated. The new process deprecates this lens-selector service.

**Comment by gmej** [comment]
@joofio do you have any github workflow that executes sushi that we can reuse for this task?

**Comment by gmej** [comment]
I would use this repo owned by @joofio as an example of a fsh/sushi project to use the same structure: https://github.com/joofio/test-epi-composition

**Comment by gmej** [comment]
This task is related and developel along with #16

**Comment by joofio** [comment]
why the overhead of sushi and not plain json?

**Comment by gmej** [comment]
we thought that potential lens developers (and us) might prefer writing fsh than json. That's the reason, but we are open for suggestions. How would you proceed with this?

**Comment by joofio** [comment]
no. fsh is niche. I would go with json which everybody knows

**Comment by aalonsolopez** [comment]
we have now the first version of our new CLI tool (which can be implemented on Actions) to bundle normal lenses to a FHIR compliant JSON file. it also have a command to upload the file to a given domain including a FHIR IPS server

**Comment by joofio** [comment]
what this mean in fact? what are "normal lenses"? what does the " it also have a command to upload the file to a given domain including a FHIR IPS server" mean?

**Comment by aalonsolopez** [comment]
Let me show you a demo video here, I'll see if I can

**Comment by aalonsolopez** [comment]
![Demo](https://github.com/Gravitate-Health/lens-selector-mvp2/assets/49404378/ce48bb09-2e6e-4e7a-be89-ba229f8b174f)

**Comment by joofio** [comment]
done
