### ISSUE TITLE
[L] Improving, debugging MVP2 lenses for MVP3

### ISSUE THREAD

**Issue by joofio** [Gravitate-Health/lens-selector-mvp2#17]

**Comment by aalonsolopez** [comment]
@joofio maybe I'm having a concept error, and kinda looks basic but... This is all the info that the IPS have. Where are supposed to be the codes related to each condition that the patient has?

**Comment by joofio** [comment]
this is not the ips. that is the patient resource. 

check IPS here:
https://gravitate-health.lst.tfo.upm.es/ips/api/fhir/Patient/$summary?identifier=ips-2
or for pedro:
https://gravitate-health.lst.tfo.upm.es/ips/api/fhir/Patient/$summary?identifier=Pedro-1

The list of IPSs we have:
https://build.fhir.org/ig/hl7-eu/gravitate-health-ips/artifacts.html

**Comment by aalonsolopez** [comment]
as I said, a concept error by my side 👍🏻 thanks joao

**Comment by aalonsolopez** [comment]
Condition Lens finished - you can see the code [here](https://github.com/Gravitate-Health/lens-selector-mvp2/blob/17-l-improving-debugging-mvp2-lenses-for-mvp3/src/lenses/lens-selector-mvp2_conditions.js) and it's connected meanwhile I'm thinking a way to make it more human readable. Eventually, we will create a "development library" to have all the logic that is repeated across lenses out of them. You can of course give feedback @joofio. Should I deploy it to dev?

**Comment by joofio** [comment]
yes it is better to deploy so i can test properly.

**Comment by aalonsolopez** [comment]
deployed :D

**Comment by joofio** [comment]
the allergy, intolerance, should be similar...

**Comment by aalonsolopez** [comment]
@joofio have you tried the lens? Is this what you expect?

**Comment by aalonsolopez** [comment]
A quick update: Pedro has no Allergy nor Intolerance.

**Comment by joofio** [comment]
try Helen https://build.fhir.org/ig/hl7-eu/gravitate-health-ips/Bundle-gravitate-helen.html
will test the other now

**Comment by joofio** [comment]
> @joofio have you tried the lens? Is this what you expect?

link to do it? like name of the lens?

**Comment by aalonsolopez** [comment]
> > @joofio have you tried the lens? Is this what you expect?
> 
> link to do it? like name of the lens?

lens-selector-mvp2_conditions

**Comment by aalonsolopez** [comment]
Should we unify Allergy and Intolerance lenses? In FHIR it's the same typo of resource....

**Comment by joofio** [comment]
yes merge them

**Comment by aalonsolopez** [comment]
okay!

**Comment by joofio** [comment]
should this work ?
```
### condition lens
POST https://gravitate-health.lst.tfo.upm.es/focusing/focus/bundlepackageleaflet-es-94a96e39cfdcd8b378d12dd4063065f9?preprocessors=preprocessing-service-manual&lenses=lens-selector-mvp2_conditions&patientIdentifier=alicia-1
```
getting 500

**Comment by aalonsolopez** [comment]
let me check why is this happening

**Comment by aalonsolopez** [comment]
Fixed

**Comment by joofio** [comment]
can we send a preprocessed epi?instead or raw

**Comment by joofio** [comment]
doesnt seem to be doing that.uploaded a test so you can try.
https://github.com/hl7-eu/gravitate-health/blob/2c9cb410cbe69a2031aad191c76648d82be22e30/tests/lenses.http#L12

**Comment by joofio** [comment]
or did you mean a identifier for a preprocessed? and not the epi?

**Comment by joofio** [comment]
with the preprocessed in the folder, they do. that why i wanted to send a preprocessed epi

**Comment by aalonsolopez** [comment]
Ah! you mean in the body?

**Comment by joofio** [comment]
> Ah! You mean in the body?

yes

**Comment by aalonsolopez** [comment]
Then the request you are trying is wrong. It's `POST https://gravitate-health.lst.tfo.upm.es/focusing/focus/?preprocessors=preprocessing-service-manual&lenses=lens-selector-mvp2_conditions&patientIdentifier=alicia-1` and the example epi in the body like this
```json
{
    "epi": <full ePI JSON>"
}
```

**Comment by joofio** [comment]
yeah it doesnt work like this. let me change the preprocessed one on the server to test

**Comment by aalonsolopez** [comment]
I'm 100% sure that this is due to the change we made to display the errors during the process on the headers in the response. With a quick change it should work because that way is meant to work.

**Comment by joofio** [comment]
ok please check that if you can. having he possibility of sending epi data will help testing

**Comment by aalonsolopez** [comment]
I will write here when I have it working 👍🏻

**Comment by aalonsolopez** [comment]
Also, I discovered that the "Accept": text/html was not working and it's also fixed

**Comment by joofio** [comment]
> Also, I discovered that the "Accept": text/html was not working and it's also fixed

doesnt seem like it . with ```content-type: application/json```returns the html.

**Comment by aalonsolopez** [comment]
Nice!

**Comment by joofio** [comment]
let me do more testing with other codes to check the full compliance. but its looking good

**Comment by aalonsolopez** [comment]
meanwhile, by the end of this week, I expect to have all the other lenses working too

**Comment by aalonsolopez** [comment]
> let me do more testing with other codes to check the full compliance. but its looking good
> 
> 
> EDIT:
> 
> the system changes and the highlight still applies. the match should be code+system
> 
> if you think it can take some time, I would prefer to solve this after all the other lenses. 
> 
> cc @aalonsolopez (made edit, not sure you get the notification)

I think I understand it

**Comment by aalonsolopez** [comment]
https://github.com/Gravitate-Health/lens-selector-mvp2/commit/e1a9e118356866318568b346bd295e7d7d02801c

Now you can try. I think it's what you want right?

**Comment by joofio** [comment]
i tested and didnt work...

**Comment by aalonsolopez** [comment]
okay I forgot to test a thing. let me fox it fast

**Comment by aalonsolopez** [comment]
Sorry, now it works (I've tested myself). Try changing the system. IDK why the automatic deploy is not working propperly.

**Comment by joofio** [comment]
now it works!

**Comment by aalonsolopez** [comment]
Go for the next lenses

**Comment by aalonsolopez** [comment]
First draft of AllergyIntollerance lens is in dev for you to try
![imagen](https://github.com/Gravitate-Health/lens-selector-mvp2/assets/49404378/5efe1bd6-f9ba-491d-95f4-0445f34f350b)

**Comment by joofio** [comment]
error
```

{
  "message": "Bad request",
  "reason": "Missing parameters"
}
```

```
POST https://gravitate-health.lst.tfo.upm.es/focusing/focus/?preprocessors=preprocessing-service-manual&lenses=lens-selector-mvp2_allergyintollerance&patientIdentifier=helen-1
content-type: application/json
Accept: application/json
#Accept: text/html

< ./examples/lactose-preproc-karvea.json
```

**Comment by aalonsolopez** [comment]
Are you using in the body this structure?
example epi in the body like this
```json
{
    "epi": <full ePI JSON>"
}
```

**Comment by joofio** [comment]
ofcourse...missing that

**Comment by aalonsolopez** [comment]
> ofcourse...missing that

Everyone has failures, I just win in "finish things" that I'm fact are not finished xD

**Comment by joofio** [comment]
seems ok!

**Comment by aalonsolopez** [comment]
OKay, I assume that the system for ingredients and contraindications on Interaction Lens should not be checked because one is the System where the Ingredient is registered. The other is the System that says it has an interaction, and will never be equal right?

**Comment by aalonsolopez** [comment]
With this doubt, Interaction Lens is finished

**Comment by joofio** [comment]
ah if the code and system should match? yes they do. the system here is like the dictionary where the code is from. is always important.

May i suggest an additional thing to this lens? (interaction)
the extension may have:
1.
```
{
            "url": "http://hl7.eu/fhir/ig/gravitate-health/StructureDefinition/HtmlElementLink",
            "extension": [
              {
                "url": "elementClass",
                "valueString": "contra-indication-hypericum"
              },
              {
                "url": "concept",
                "valueCodeableReference": {
                  "concept": {
                    "coding": [
                      {
                        "code": "XK4IUX8MNB",
                        "system": "https://gsrs.ncats.nih.gov/ginas/app/beta",
                        "display": "Hypericum perforatum L."
                      }
                    ]
                  }
                }
              }
            ]
          },
```

2.
```
          {
            "url": "http://hl7.eu/fhir/ig/gravitate-health/StructureDefinition/HtmlElementLink",
            "extension": [
              {
                "url": "elementClass",
                "valueString": "contra-indication-pregnancy"
              },
              {
                "url": "concept",
                "valueCodeableReference": {
                  "reference": {
                    "reference": "ClinicalUseDefinition/contraindication-pregnancy"
                  }
                }
              }
            ]
          },
```

could we lookup the clinicalusedefinition to check the code there?

the direct one (1) seems ok!

**Comment by joofio** [comment]
done for improving logic and making the mvp2 lenses work. bugfixing will be handled bug to bug
