### ISSUE TITLE
Change logic to use identifier as id instead of name

### ISSUE THREAD

**Issue by joofio** [Gravitate-Health/lens-selector-mvp2#24]
use identifier as id and not name. Name should be a human readable string

**Comment by aalonsolopez** [comment]
https://fosps.gravitatehealth.eu/focusing/lenses

These are the Identifiers of the lenses.

**Comment by joofio** [comment]
example from :
`POST https://gravitate-health.lst.tfo.upm.es/focusing/focus/processedbundlekarveabik?preprocessors=preprocessing-service-mvp2&preprocessors=preprocessing-service-manual&patientIdentifier=alicia-1  
Accept: application/json
content-type: application/json  
`

returns:
` <span class=\"indication highlight conditions-lens\">of human immunodeficiency virus 1 (HIV-1) infection in adults, adolescents and children 2 years of age and older, who weigh at least 14 kg.</span></p><p>Biktarvy reduces the amount of HIV in your body. This will improve your immune system and reduce the risk of developing illnesses linked to HIV infection.</p></div>"`
