### ISSUE TITLE
Change lenses to be totally agnostic to the tags

### ISSUE THREAD

**Issue by aalonsolopez** [Gravitate-Health/lens-selector-mvp2#3]
At this time, some lenses only search for <span> tags, and due to some errors found it should search for any element that has the class that we search

**Comment by aalonsolopez** [comment]
@joofio when you can if you have something to add, feel free to write here :)

**Comment by aalonsolopez** [comment]
Making a short research we've seen that the best option to make the lenses agnostic to the tag that needs the highlight, the best option is to abandon the idea of using RegExp to reuse the search algorithm that we maked in the automatic preprocessor (that is not yet ready to use). Develop and testing this could take a few days.

**Comment by joofio** [comment]
can we change for div for the time being in order to make it easier to test?
and then in the medium term, agnostic?

**Comment by aalonsolopez** [comment]
we can change for div, of course

**Comment by joofio** [comment]
so, im my opinion we could go for div harcoded today and in the next few days use the agnstoic

**Comment by aalonsolopez** [comment]
i make the change, we leave this issue opened, and I work in the feature today and in the next days

**Comment by joofio** [comment]
perfect!

**Comment by amedranogil** [comment]
the specification, just reminding everyone, includes any HTML tag, the selection (for annotation, highlighting or suppressing) condition should only consider the attributes of the tag, not the type of tag. There fore the end goal should be to support span, div, h1, h2, and any HTML tag.

**Comment by joofio** [comment]
i agree with this and i think that it will be beneficial in the long term since we want to accomodate the largest number of lenses possbile

**Comment by aalonsolopez** [comment]
@joofio I will apply this commit to override the "lens-selector-mvp2" service. I've tested it on my local machine and it works as expected.

**Comment by aalonsolopez** [comment]
Detected failure on conditional import. I expect to solve it as soon as possible as I've found a solution (that I've to learn how to implement)

**Comment by aalonsolopez** [comment]
This issue is entering on "testing" phase. When we finish the test plan, we make a pull request to main and we deploy it.

**Comment by aalonsolopez** [comment]
Due to unexpected error on lenses, this is reopened. With the next change should be fixed.

**Comment by aalonsolopez** [comment]
Problem on https://github.com/Gravitate-Health/fhir-connector/issues/2 should be fixed rn. Change is live on FOSPS
