### ISSUE TITLE
Improve lens catalog return values of swagger

### ISSUE THREAD

**Issue by joofio** [Gravitate-Health/lens-selector-mvp2#7]
Do not know if this is the place to add this but feel free to change if needed.

current response for : ```GET https://fosps.gravitatehealth.eu/focusing/lenses```

```
{
  "lenses": [
    "lens-selector-div_HIV",
    "lens-selector-div_diabetes",
    "lens-selector-div_pregnancy",
    "lens-selector-mvp2_HIV",
    "lens-selector-mvp2_diabetes",
    "lens-selector-mvp2_pregnancy"
  ]
}
```

I suggest adding at least two more fields for each lens:
1- a small description of what it doest
2- codes taken into account if any.

**Comment by aalonsolopez** [comment]
Now that is transfered, @joofio you expect that the JSON that returns the endpoint  ```GET https://fosps.gravitatehealth.eu/focusing/lenses```with all the lenses available bring a short description of what it does and the codes it searches?

**Comment by joofio** [comment]
thanks for the transfer.

Yes, I think more detail would be important. At least a short description
of what it does..

Alejandro Alonso ***@***.***> escreveu no dia sexta,
6/10/2023 à(s) 09:47:

**Comment by aalonsolopez** [comment]
Perfect. Once reworked lenses are confirmed to be OK, then I will make them more understandable :)

**Comment by 10alejospain** [comment]
I sugest to make the "advance info about lenses" in another endpoint so it's not breaking anything working rn

**Comment by aalonsolopez** [comment]
> I sugest to make the "advance info about lenses" in another endpoint so it's not breaking anything working rn

Working on this solution rn

**Comment by gmej** [comment]
> I sugest to make the "advance info about lenses" in another endpoint so it's not breaking anything working rn

totally agree. I would do GET to lenses/info and get the metadata for the lenses instead of the lenses themselves.

**Comment by gmej** [comment]
Will be done in [gravitate-health/29](https://github.com/hl7-eu/gravitate-health/issues/29)
